title: MATH 565 Monte Carlo Methods, Fall 2025
markdown: kramdown
theme: minima

exclude:
  - qmcsoftware
  - .gitmodules
  - .gitignore
  - README.md

url: "https://qmcsoftware.github.io"
baseurl: "/MATH565Fall2025"
repo_owner: QMCSoftware
repo_name: MATH565Fall2025
repo_branch: main

sass:
  style: compressed

plugins:
  - jekyll-last-modified-at

# Defaults
defaults:
  - scope:
      path: ""
    values:
      layout: default
      css: "/assets/css/style.css"
  - scope:
      path: "assignments"
      type: "assignments"
    values:
      layout: default

# Collections
collections:
  assignments:
    output: true
    permalink: /assignments/:name/

# Clean URLs for regular pages too
permalink: /:path/