title: MATH 565 Monte Carlo Methods, Fall 2025
markdown: kramdown
theme: minima
exclude:
  - qmcsoftware
  - .gitmodules
  - .gitignore
  - README.md

url: "https://QMCPySoftware.github.io"
baseurl: "/MATH565Fall2025"

sass:
  style: compressed

plugins:
  - jekyll-last-modified-at

# Use custom stylesheet
defaults:
  -
    scope:
      path: ""
    values:
      layout: default
      css: "/assets/css/style.css"

header_pages:
  - syllabus.md