title: MATH 565 Monte Carlo Methods, Fall 2025
markdown: kramdown
theme: minima
exclude:
  - qmcsoftware
  - .gitmodules
  - .gitignore
  - README.md

sass:
  style: compressed

# Use custom stylesheet
defaults:
  -
    scope:
      path: ""
    values:
      layout: default
      css: "/assets/css/style.css"

header_pages:
  - syllabus.md